name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libft-dev

      - name: Build push_swap
        run: |
          make

      # Run tests (if you have a testing setup)
      - name: Run tests
        run: |
          ./push_swap 3 2 1
          echo "Running tests..."
